
services:
  database:
    container_name: mongodb-test
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
      - ./init.mongo.js:/docker-entrypoint-initdb.d/init.mongo.js:ro
    healthcheck:
      test: |
        mongosh \
          --host localhost \
          --quiet \
          --eval 'quit(db.adminCommand("ping").ok ? 0 : 1)'
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s


  backend:
    container_name: toysRUs-backend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=compose
    build: ./backend
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: toysRUs-frontend
    ports:
      - 4200:80
    build: ./frontend